baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Austin Quam - 4662W"
theme = "hugo-uno"

contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
author = "Austin Quam"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. - Fredrik Loch"


[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Austin"
  github = "redact-d"
  twitter = "redactd"
  email = "quamx110@gmail.com"
  description = "This site will work as a publishing platform for security information as well as offering links to Austin's various social networks. It is still a draft"
  cv = "/pages/cv"
  legalnotice = "/pages/legal-notice"
  linkedin = "austinq"
  cover = "/images/back.png"
  logo = "/images/aweb.png"
